version: "3"
services:
  app:
    image: tupi4ok/rent_image:latest
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_NAME: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: