name: Java CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: "development"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradlew executable
        run: chmod +x ${{github.workspace}}/app/gradlew
        working-directory: app
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
           CC_TEST_REPORTER_ID: ${{secrets.TESTCOVERAGE}}
           JACOCO_SOURCE_PATH: app/src/main/java
        with:
           coverageCommand: make report
           coverageLocations: ${{github.workspace}}/app/build/reports/jacoco/test/jacocoTestReport.xml:jacoco
